name: Build and Test PMSF

on:
  push:
    branches:
      - dec2024
  pull_request:
    branches:
      - dec2024

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up PHP (with Composer)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, pdo_mysql, curl

    # Install Composer dependencies
    - name: Install PHP dependencies with Composer
      run: |
        composer install --dev

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install Node.js dependencies
    - name: Install Node.js dependencies with npm
      run: |
        npm install

    # Run build commands (Grunt)
    - name: Run Grunt build
      run: |
        npm run build

#    # Run PHP tests (assuming PHPUnit is used)
#    - name: Run PHP tests
#      run: |
#        vendor/bin/phpunit
